[2023-11-26T05:15:25.906+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-23T00:00:00+00:00/task_id=step1 permission to 509
[2023-11-26T05:15:26.096+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-23T00:00:00+00:00/task_id=step1 permission to 509
[2023-11-26T05:15:26.224+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.step1 scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26T05:15:26.256+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.step1 scheduled__2023-11-23T00:00:00+00:00 [queued]>
[2023-11-26T05:15:26.268+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T05:15:26.326+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): step1> on 2023-11-23 00:00:00+00:00
[2023-11-26T05:15:26.350+0000] {standard_task_runner.py:57} INFO - Started process 80 to run task
[2023-11-26T05:15:26.355+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'step1', 'scheduled__2023-11-23T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmpveinngbr']
[2023-11-26T05:15:26.366+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask step1
[2023-11-26T05:15:27.419+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=scheduled__2023-11-23T00:00:00+00:00/task_id=step1 permission to 509
[2023-11-26T05:15:27.432+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.step1 scheduled__2023-11-23T00:00:00+00:00 [running]> on host 42136bd2bf4d
[2023-11-26T05:15:28.200+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='step1' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-23T00:00:00+00:00'
[2023-11-26T05:15:28.232+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-26T05:15:28.239+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/data/2023-11-23/downloads                         ls -ld']
[2023-11-26T05:15:28.290+0000] {subprocess.py:86} INFO - Output:
[2023-11-26T05:15:28.309+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: too many arguments
[2023-11-26T05:15:28.313+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-26T05:15:28.394+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-26T05:15:28.433+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=step1, execution_date=20231123T000000, start_date=20231126T051526, end_date=20231126T051528
[2023-11-26T05:15:28.555+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task step1 (Bash command failed. The command returned a non-zero exit code 1.; 80)
[2023-11-26T05:15:28.751+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T05:15:30.203+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
