[2023-11-26T05:16:58.165+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T05:16:57.096283+00:00/task_id=step1 permission to 509
[2023-11-26T05:16:58.200+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T05:16:57.096283+00:00/task_id=step1 permission to 509
[2023-11-26T05:16:58.231+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag.step1 manual__2023-11-26T05:16:57.096283+00:00 [queued]>
[2023-11-26T05:16:58.242+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag.step1 manual__2023-11-26T05:16:57.096283+00:00 [queued]>
[2023-11-26T05:16:58.244+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T05:16:58.259+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): step1> on 2023-11-26 05:16:57.096283+00:00
[2023-11-26T05:16:58.265+0000] {standard_task_runner.py:57} INFO - Started process 114 to run task
[2023-11-26T05:16:58.268+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag', 'step1', 'manual__2023-11-26T05:16:57.096283+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/outcomes_dag.py', '--cfg-path', '/tmp/tmp0gqy9_ph']
[2023-11-26T05:16:58.270+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask step1
[2023-11-26T05:16:58.329+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag/run_id=manual__2023-11-26T05:16:57.096283+00:00/task_id=step1 permission to 509
[2023-11-26T05:16:58.333+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag.step1 manual__2023-11-26T05:16:57.096283+00:00 [running]> on host 42136bd2bf4d
[2023-11-26T05:16:58.576+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag' AIRFLOW_CTX_TASK_ID='step1' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T05:16:57.096283+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T05:16:57.096283+00:00'
[2023-11-26T05:16:58.578+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-26T05:16:58.579+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -create-dirs -o /opt/***/data/2023-11-26/downloads/outcomes_2023-11-26.csv https://data.austintexas.gov/api/views/9t4d-g238/rows.csv']
[2023-11-26T05:16:58.589+0000] {subprocess.py:86} INFO - Output:
[2023-11-26T05:16:58.597+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2023-11-26T05:16:58.598+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2023-11-26T05:17:00.634+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Failed to create the file
[2023-11-26T05:17:00.635+0000] {subprocess.py:93} INFO - Warning: /opt/***/data/2023-11-26/downloads/outcomes_2023-11-26.csv: No
[2023-11-26T05:17:00.636+0000] {subprocess.py:93} INFO - Warning: such file or directory
[2023-11-26T05:17:00.638+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
[2023-11-26T05:17:00.639+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2023-11-26T05:17:00.641+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2023-11-26T05:17:00.669+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2023-11-26T05:17:00.683+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=outcomes_dag, task_id=step1, execution_date=20231126T051657, start_date=20231126T051658, end_date=20231126T051700
[2023-11-26T05:17:00.715+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task step1 (Bash command failed. The command returned a non-zero exit code 23.; 114)
[2023-11-26T05:17:00.737+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T05:17:00.759+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
