[2023-11-26T05:35:43.755+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag1/run_id=scheduled__2023-11-25T00:00:00+00:00/task_id=LOAD_FCT_OUTCOMES permission to 509
[2023-11-26T05:35:43.787+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag1/run_id=scheduled__2023-11-25T00:00:00+00:00/task_id=LOAD_FCT_OUTCOMES permission to 509
[2023-11-26T05:35:43.815+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: outcomes_dag1.LOAD_FCT_OUTCOMES scheduled__2023-11-25T00:00:00+00:00 [queued]>
[2023-11-26T05:35:43.827+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: outcomes_dag1.LOAD_FCT_OUTCOMES scheduled__2023-11-25T00:00:00+00:00 [queued]>
[2023-11-26T05:35:43.829+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-26T05:35:43.968+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): LOAD_FCT_OUTCOMES> on 2023-11-25 00:00:00+00:00
[2023-11-26T05:35:43.975+0000] {standard_task_runner.py:57} INFO - Started process 447 to run task
[2023-11-26T05:35:43.977+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'outcomes_dag1', 'LOAD_FCT_OUTCOMES', 'scheduled__2023-11-25T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/Retry2.py', '--cfg-path', '/tmp/tmptfbcf763']
[2023-11-26T05:35:43.980+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask LOAD_FCT_OUTCOMES
[2023-11-26T05:35:44.028+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=outcomes_dag1/run_id=scheduled__2023-11-25T00:00:00+00:00/task_id=LOAD_FCT_OUTCOMES permission to 509
[2023-11-26T05:35:44.033+0000] {task_command.py:416} INFO - Running <TaskInstance: outcomes_dag1.LOAD_FCT_OUTCOMES scheduled__2023-11-25T00:00:00+00:00 [running]> on host 42136bd2bf4d
[2023-11-26T05:35:44.104+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='outcomes_dag1' AIRFLOW_CTX_TASK_ID='LOAD_FCT_OUTCOMES' AIRFLOW_CTX_EXECUTION_DATE='2023-11-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-25T00:00:00+00:00'
[2023-11-26T05:35:44.901+0000] {logging_mixin.py:154} INFO - Executing Create Table Queries...
[2023-11-26T05:35:44.965+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ExtractTransformLoad_Steps/LoadData.py", line 153, in load_data_to_postgres
    postgres_dataloader.create_table(postgres_connection, table_query)
  File "/opt/airflow/dags/ExtractTransformLoad_Steps/LoadData.py", line 121, in create_table
    cursor.execute(table_query)
psycopg2.errors.InvalidForeignKey: there is no unique constraint matching given keys for referenced table "animaldimension"

[2023-11-26T05:35:44.994+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=outcomes_dag1, task_id=LOAD_FCT_OUTCOMES, execution_date=20231125T000000, start_date=20231126T053543, end_date=20231126T053544
[2023-11-26T05:35:45.016+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task LOAD_FCT_OUTCOMES (there is no unique constraint matching given keys for referenced table "animaldimension"
; 447)
[2023-11-26T05:35:45.039+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T05:35:45.063+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
